services:
  postgres-campoInteligente:
    container_name: postgres-campoInteligente
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER_BD}
      POSTGRES_PASSWORD: ${DB_PASSWORD_BD}
      POSTGRES_DB: ${DB_NAME_BD}
    volumes:
      #- ./initdb:/docker-entrypoint-initdb.d
      #- ./data/postgres:/var/lib/postgresql/data
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/pgadmin_config/servers.json:/pgadmin4/servers.json

  evolution-api:
    container_name: evolution-api
    image: atendai/evolution-api:v1.8.2
    restart: always
    ports:
      - "8085:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  evolution_instances:
  pgadmin_data:
