name: Executar Delete Failed Workflow Runs

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Deletar execuções de workflow com falha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo="${{ github.repository }}"
          per_page=100
          page=1

          while true; do
            response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$repo/actions/runs?per_page=$per_page&page=$page")

            runs=$(echo "$response" | jq '.workflow_runs')
            if [[ "$runs" == "[]" || -z "$runs" ]]; then
              echo "✅ Nenhuma execução restante para verificar."
              break
            fi

            echo "$response" | jq -c '.workflow_runs[]' | while read -r run; do
              id=$(echo "$run" | jq -r '.id')
              status=$(echo "$run" | jq -r '.conclusion')

              if [[ "$status" == "failure" || "$status" == "cancelled" ]]; then
                curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                  "https://api.github.com/repos/$repo/actions/runs/$id"
                echo "🗑️ Deletado run ID: $id com status: $status"
              fi
            done

            ((page++))
          done
