name: Deploy on main push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy para o servidor
        run: |
          ssh -p 21022 marcosmorais@campointeligente.ddns.com.br << 'EOF'
            set -e
            cd /var/www/campointeligente-back
            ./atualizar-campo.sh
          EOF
