
name: Sync to CampoInteligente

on:
  push: # Gatilho para executar ao receber commits
    branches:
      - main # Executa apenas se o push for na branch main
  schedule:
    - cron: "*/30 * * * *" # Executa a cada 30 minutos
  workflow_dispatch: # Permite execução manual

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Git
        run: |
          git config --global user.name "Marcos Morais"
          git config --global user.email "marcosmoraisjr@users.noreply.github.com"
      - name: Clonar repositório de origem
        run: |
          git clone https://marcosmoraisjr:${{ secrets.GH_PAT }}@github.com/restic36/startup-campo-inteligente-back.git source
          cd source
          git remote add destino https://marcosmoraisjr:${{ secrets.GH_PAT }}@github.com/marcosmoraisjr/CampoInteligente-back.git
          git push --force destino main
