name: Sync to CampoInteligente

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Git
        run: |
          git config --global user.name "Marcos Morais"
          git config --global user.email "marcosmoraisjr@users.noreply.github.com"

      - name: Configurar ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clonar repositório de origem via SSH
        run: |
          git clone git@github.com:restic36/startup-campo-inteligente-back.git source
          cd source
          git remote add destino git@github.com:marcosmoraisjr/CampoInteligente-back.git
          git push --force destino main
